### ISSUE TITLE
:farmer: `DetachableJointTest.CorrectAttachmentPoints` test failing consistently in gz-physics6-homebrew

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-physics#626] opened 2024-04-18 14:57 UTC
## Environment
* OS Version: MacOS (Ventura and Monterey)
* Source build: Garden

## Description
* Expected behavior: Tests should pass
* Actual behavior: [DetachableJointTest/0.CorrectAttachmentPoints](https://build.osrfoundation.org/job/gz_physics-ci-gz-physics6-homebrew-amd64/35/testReport/junit/(root)/DetachableJointTest_0/CorrectAttachmentPoints/) is failing in gz_physics6

## Steps to reproduce
1. Run a build
2. See test fail

## Output

Reference builds: 
* https://build.osrfoundation.org/job/gz_physics-ci-gz-physics6-homebrew-amd64/35/

Failing test regression: [DetachableJointTest/0.CorrectAttachmentPoints](https://build.osrfoundation.org/job/gz_physics-ci-gz-physics6-homebrew-amd64/35/testReport/junit/(root)/DetachableJointTest_0/CorrectAttachmentPoints/)
```
/Users/jenkins/jenkins-agent/workspace/gz_physics-ci-gz-physics6-homebrew-amd64/gz-physics/test/common_test/detachable_joint.cc:190
The difference between 0.15 and frameDataC1L1.pose.translation().z() is 0.10148802840906343, which exceeds 1e-2, where
0.15 evaluates to 0.14999999999999999,
frameDataC1L1.pose.translation().z() evaluates to 0.048511971590936565, and
1e-2 evaluates to 0.01.

```

Test hasn't been modified for 6 months. It was added in: https://github.com/gazebosim/gz-physics/pull/530

Could be related to https://github.com/gazebosim/gz-physics/issues/620?

**Comment by scpeters** [comment] 2024-04-18 17:27
this test has been disabled in https://github.com/gazebosim/gz-physics/pull/621, which should be backported to `gz-physics6`

**Comment by azeey** [comment] 2024-05-06 22:08
@Crola1702 would you be able to do the backport or do you need @scpeters's help?

**Comment by scpeters** [comment] 2024-05-07 12:28
> this test has been disabled in #621, which should be backported to `gz-physics6`

sorry I got mixed up. This issue is a duplicate of https://github.com/gazebosim/gz-physics/issues/612, which was fixed by https://github.com/Homebrew/homebrew-core/pull/167721

no more backports are needed here

**Closed by scpeters** 2024-05-07 12:28 UTC
Labels: bug
