### ISSUE TITLE
Crash with assertion failure "aabbBound >= dMinIntExact && aabbBound < dMaxIntExact"

### ISSUE THREAD

**Issue by gzfuzz** [gazebosim/gz-physics#661] opened 2024-07-01 04:21 UTC
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build?
    source build
    gz-sim version: 5641ef2cc7bed13e06892d29ffd3663b2f172e76
    gz-physics version: f54d4ded615626d3cff34a5dcfa0cedfe8bd903f
    built with 
    gcc version: 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
    build options: -DCMAKE_BUILD_TYPE=Coverage

## Description
* Expected behavior: Gazebo doesn't crash
* Actual behavior: Gazebo crashes
 
## Steps to reproduce:

1. tar xf [a.tar.gz](https://github.com/user-attachments/files/16047867/a.tar.gz)

2. gz sim buggy.sdf -r

## Output

[a.log](https://github.com/user-attachments/files/16047870/a.log)

**Comment by azeey** [comment] 2024-07-22 22:13
This is a duplicate of https://github.com/gazebosim/gz-sim/issues/15. It seems like this happens when objects are so far away from the origin that they don't fit in the bounding box created by ode's collision detection code. But I don't understand why the objects move that far in the first place.

**Closed** 2024-12-19 20:32 UTC
Labels: bug, help wanted
